name: Build & publish project

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
      - 'CMakeLists.txt'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
      - 'CMakeLists.txt'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest

    env:
      PROGRAM_VERSION: ${{ github.event.release.tag_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify tools
        run: |
          clang-cl --version
          cmake --version

      - name: Configure (Debug)
        run: >
          cmake
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE
          -DCMAKE_C_COMPILER="C:\Program Files\LLVM\bin\clang-cl.exe"
          -DCMAKE_CXX_COMPILER="C:\Program Files\LLVM\bin\clang-cl.exe"
          -S "${{ github.workspace }}"
          -B "${{ github.workspace }}\build"
          -G "Ninja"

      - name: Build (Debug)
        run: >
          cmake
          --build "${{ github.workspace }}\build"
          --config Debug
          --target all

      - name: Configure (Release)
        if: success() && github.event_name == 'release' && github.event.action == 'published'
        run: >
          cmake
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE
          -DCMAKE_C_COMPILER="C:\Program Files\LLVM\bin\clang-cl.exe"
          -DCMAKE_CXX_COMPILER="C:\Program Files\LLVM\bin\clang-cl.exe"
          -S "${{ github.workspace }}"
          -B "${{ github.workspace }}\build"
          -G "Ninja"

      - name: Build (Release)
        if: success() && github.event_name == 'release' && github.event.action == 'published'
        run: >
          cmake
          --build "${{ github.workspace }}\build"
          --config Release
          --target all

      - name: Package builds
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          7z a ImageViewer_debug-${{ github.event.release.tag_name }}.zip .\output\Debug\*
          7z a ImageViewer_release-${{ github.event.release.tag_name }}.zip .\output\Release\*

      - name: Publish GitHub Release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: "ImageViewer ${{ github.event.release.tag_name }}"
          body_path: FEATURES.md
          files: |
            ImageViewer_release-${{ github.event.release.tag_name }}.zip
            ImageViewer_debug-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}