name: Test build
on:
  push:
    branches:
      - '**'
    paths:
      - 'src/**'
      - '.github/workflows/debug.yml'
      - 'CMakeLists.txt'
      - 'vcpkg.json'
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/**'
      - '.github/workflows/debug.yml'
      - 'CMakeLists.txt'
      - 'vcpkg.json'

permissions:
  contents: read

jobs:
  debug-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify tools
        run: |
          clang-cl --version
          cmake --version

      - name: Restore cached Primes
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}\build
          key: ${{ runner.os }}-build-cache-${{ hashFiles('CMakeLists.txt', 'vcpkg.json') }}

      - name: Configure (Debug)
        run: >
          cmake
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE
          -DCMAKE_C_COMPILER="C:\Program Files\LLVM\bin\clang-cl.exe"
          -DCMAKE_CXX_COMPILER="C:\Program Files\LLVM\bin\clang-cl.exe"
          -S "${{ github.workspace }}"
          -B "${{ github.workspace }}\build"
          -G "Ninja"

      - name: Build (Debug)
        run: >
          cmake
          --build "${{ github.workspace }}\build"
          --config Debug
          --target all

      - name: Configure (Release)
        if: github.event_name != 'pull_request'
        run: >
          cmake
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE
          -DCMAKE_C_COMPILER="C:\Program Files\LLVM\bin\clang-cl.exe"
          -DCMAKE_CXX_COMPILER="C:\Program Files\LLVM\bin\clang-cl.exe"
          -S "${{ github.workspace }}"
          -B "${{ github.workspace }}\build"
          -G "Ninja"

      - name: Build (Release)
        if: github.event_name != 'pull_request'
        run: >
          cmake
          --build "${{ github.workspace }}\build"
          --config Release
          --target all

      - name: Save Primes
        if: steps.cache-restore.outputs.cache-hit != 'true' && github.event_name != 'pull_request'
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}\build
          key: ${{ runner.os }}-build-cache-${{ hashFiles('CMakeLists.txt', 'vcpkg.json') }}